### ISSUE TITLE
Morning_session

### ISSUE THREAD

**Issue by AndreaM2429** [cancelei/Portfolio-Option-2#7]
The code is excellent, it looks clean and orginized but there are some areas that could be improve, such as:
- Create a class for a repetitive setting
- Use one media query per screen size 
- Avoid repeat the font family and size

**Comment by MohamedRoshdy2021** [comment]
the code looks fantastic but I have a small suggestion 
- please modify px units from px to maybe rem units for more responsiveness

**Comment by Roathy** [comment]
Your project looks great, there may be a little improvement in the HTML file
Maybe consider using the main tag for the main content of your website instead of a generic section tag.
